[SPAGHETTIKART] Make otrgen more robust

diff --git a/ports/released/harbourmasters/spaghettikart/spaghettikart/tools/otrgen b/ports/released/harbourmasters/spaghettikart/spaghettikart/tools/otrgen
--- a/ports/released/harbourmasters/spaghettikart/spaghettikart/tools/otrgen
+++ b/ports/released/harbourmasters/spaghettikart/spaghettikart/tools/otrgen
@@ -18,6 +18,7 @@ emit_fail_msg() {
     echo "PATCH_FAIL_MSG:$1" >&3
     echo "$1"
     FAIL_MSG_SET=1
+    echo "Patching process failed!"
 }
 
 echo "GAMEDIR is set to: $GAMEDIR"
@@ -27,7 +28,7 @@ unzip_assets() {
     # Define 7zzs binary
     SEVENZIP="$controlfolder/7zzs.${DEVICE_ARCH}"
     if [ ! -x "$SEVENZIP" ]; then
-        emit_fail_msg "7zzs binary not found at $SEVENZIP"
+        emit_fail_msg "[OTRGEN] 7zzs binary not found at $SEVENZIP"
         return 1
     fi
 
@@ -48,21 +49,22 @@ process_rom() {
     local input_file="$1"
     if [ ! -f "../baseroms/$input_file" ]; then
         emit_fail_msg "[OTRGEN] Error: File $input_file not found!"
-        exit 1
+        return 1
     fi
 
     # Run the extraction
-    echo "Extracting data from ../baseroms/$input_file..."
-    if ./torch header -o "../baseroms/$input_file" > /dev/null; then
-        if ./torch o2r "../baseroms/$input_file" --additional-files meta/mods.toml >> "$LOGFILE"; then
+    echo "Extracting data from $GAMEDIR/baseroms/$input_file..."
+    if ./torch header -o "$GAMEDIR/baseroms/$input_file" > /dev/null; then
+        if ./torch o2r "$GAMEDIR/baseroms/$input_file" --additional-files meta/mods.toml >> "$LOGFILE"; then
             echo "[OTRGEN] Extraction complete. O2R generated."
-            mv mk64.o2r ../mk64.o2r
+            rm -rf "$GAMEDIR/mk64.o24"
+            mv mk64.o2r "$GAMEDIR/mk64.o2r"
         else
-            emit_fail_msg "[OTRGEN] Error: O2R generation failed for ../baseroms/$input_file."
-            exit 1
+            emit_fail_msg "[OTRGEN] Error: O2R generation failed for $GAMEDIR/baseroms/$input_file."
+            return 1
         fi
     else
-        echo "[OTRGEN] Error: Header extraction failed for ../baseroms/$input_file."
+        echo "[OTRGEN] Error: Header extraction failed for $GAMEDIR/baseroms/$input_file."
     fi
     cd "$GAMEDIR"
 }
@@ -72,7 +74,7 @@ convert_n64() {
     local rom_file="$1"
     local base_name
     base_name=$(basename "$rom_file")
-    local output_file="baseroms/${base_name%.*}.z64"
+    local output_file="$GAMEDIR/baseroms/${base_name%.*}.z64"
 
     if [[ ! -f "$rom_file" ]]; then
         emit_fail_msg "Error: File $rom_file not found!"
@@ -110,8 +112,7 @@ rom_file=$(find "$GAMEDIR/baseroms" -maxdepth 1 \( -name "*.z64" -o -name "*.n64
 
 # Test if regenerating o2r
 if [ -n "$REGEN" ] && [ ! -f "$ASSETS_ZIP" ]; then
-    [ -z "$FAIL_MSG_SET" ] && emit_fail_msg "Patching failed. Report on the RHH-Ports GitHub with patcherr.txt."
-    echo "Patching process failed!"
+    [ -z "$FAIL_MSG_SET" ] && emit_fail_msg "[OTRGEN] You are trying to regenerate your o2r with old assets manifests. Add assets.zip to the tools folder and try again."
     exit 1
 fi
 
@@ -128,12 +129,12 @@ echo "Processing $rom_file..."
 
 case "$rom_file" in
     *.n64)
-        converted_file=$(convert_n64 "$rom_file") || { echo "Patching process failed!"; exit 1; }
+        converted_file=$(convert_n64 "$rom_file") || exit 1;
         rm -f "$rom_file"
-        process_rom "$(basename "$converted_file")"  || { echo "Patching process failed!"; exit 1; }
+        process_rom "$(basename "$converted_file")" || exit 1;
         ;;
     *.z64)
-        process_rom "$(basename "$rom_file")"  || { echo "Patching process failed!"; exit 1; }
+        process_rom "$(basename "$rom_file")" || exit 1;
         ;;
 esac
 
